#DEFINE PIN_SD_MISO 13
#DEFINE PIN_SD_SCK 12
#DEFINE PIN_SD_MOSI 11
#DEFINE PIN_SD_CS 10
#DEFINE PIN_SONAR_TRIG 8
#DEFINE PIN_SONAR_ECHF 7
#DEFINE PIN_SONAR_ECHR 4
#DEFINE PIN_SONAR_ECHF 2

void setup() {

}
void loop() {

}