#define PIN_SD_MISO 13
#define PIN_SD_SCK 12
#define PIN_SD_MOSI 11
#define PIN_SD_CS 10
#define PIN_FAN_PWM 9
#define PIN_SONAR_TRIG 8
#define PIN_MOT1_DIR 7
#define PIN_MOT1_EN 6
#define PIN_MOT2_EN 5
#define PIN_MOT2_DIR 4
#define PIN_SONAR_ECHF A0
#define PIN_SONAR_ECHR A1
#define PIN_SONAR_ECHL A2